// This file was auto-generated by prisma-generator-typescript-interfaces

export interface Website {
  id: number;
  baseUrl: string;
  title: string;
  logo: string;
  except: string;
  isDeleted: boolean;
  createdDt: Date | null;
  updatedDt: Date | null;
  isAdultOnly: boolean;
  Error?: Error[];
  Category?: CategoryOnWebsite[];
  Tag?: TagOnWebsite[];
}

export interface Image {
  id: number;
  caption: string | null;
  fileName: string;
  createdDt: Date | null;
  Category?: Category[];
}

export interface Category {
  id: number;
  name: string;
  order: number;
  imageId: number | null;
  image?: Image | null;
  CategoryOnWebsite?: CategoryOnWebsite[];
}

export interface CategoryOnWebsite {
  id: number;
  websiteId: number;
  categoryId: number;
  Website?: Website;
  Category?: Category;
}

export interface Tag {
  id: number;
  name: string;
  order: number;
  imageId: number | null;
  TagOnWebsite?: TagOnWebsite[];
}

export interface TagOnWebsite {
  id: number;
  websiteId: number;
  tagId: number;
  Website?: Website;
  Tag?: Tag;
}

export interface Error {
  id: number;
  httpCode: number;
  message: string;
  stack: string;
  websiteId: number;
  userIp: string;
  createdDt: Date | null;
  Website?: Website;
}

export interface FakeMeta {
  id: number;
  title: string;
  description: string;
  ogImageUrl: string;
  redirectUrl: string;
  createdDt: Date | null;
}

export interface VisitLog {
  id: number;
  visitorId: number;
  trackCode: string;
  fullUrl: string;
  userIp: string;
  userAgent: string;
  screenResolution: string;
  latitude: number | null;
  longitude: number | null;
  accuracy: number | null;
  createdDt: Date | null;
  Visitor?: Visitor;
}

export interface Visitor {
  id: number;
  uid: string;
  nickname: string;
  userIp: string;
  userAgent: string;
  createdDt: Date | null;
  VisitLog?: VisitLog[];
}
